version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ broker port
      - "15672:15672" # RabbitMQ management console port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  golang_api:
    image: golang:1.23.3
    container_name: golang-api
    build:
      context: ./golang_api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./golang_api:/app
    working_dir: /app
    command: ./app
    depends_on:
      - rabbitmq
      - mongodb

  golang_worker:
    image: golang:1.23.3
    container_name: golang-worker
    build:
      context: ./golang_worker
      dockerfile: Dockerfile
    volumes:
      - ./golang_worker:/app
    working_dir: /app
    command: ./app
    depends_on:
      - rabbitmq
      - mongodb

  nextjs:
    image: node:22-bullseye
    container_name: nextjs-service
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs:/app
      - /app/node_modules
    working_dir: /app/dashboard
    command: sh -c "npm install && npm run dev"
    depends_on:
      - rabbitmq
      - mongodb
